### PR TITLE
Working version in NCFM cititruck4

### PR DESCRIPTION
**Pull request by MFernandezCarmona**
Most of the changes are to support parametrization of the topics/tfs. I have also modified the xacro files to include the released package containing kinect2 and asus xtion and other minor files.
Anyway, let's discus the changes

### CODE REVIEW

**Comment by MFernandezCarmona** [comment]
Release fails because is looking for asus_description package. 

WHY: That one is part of repository https://github.com/LCAS/depth_sensors , already released as a deb package. However, "asus_description" is not listed in https://github.com/LCAS/rosdistro/blob/master/kinetic/lcas-dist.yaml as provided by "depth_sensors" 

SOLUTION: add asus_description to lcas-dist.yaml and retrigger a release of detpth_sensors package in LCAS distro. @marc-hanheide  can you tell me how to do it?

**Comment by marc-hanheide** [comment]
We'll discuss in person shortly

**Comment by marc-hanheide** [comment]
we have re-releases `depth_sensor` and afterwards this should be retested

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
Just triggered the retest as `asus_description` is now available

**Review by marc-hanheide — APPROVED** [review]
looks fine and PR build succeeded

**Comment by marc-hanheide** [comment]
Is it time to trigger a new release yet? Or are there more changes to be done before the NCFM event?

**Comment by h72a65** [comment]
I merged some calibration. Hope I didn't screw anything up. I want to make sure that the examples in the README.md file runs as the should - they do that partially now but there are some topics that needs some fixing. When this is done I think it's time for a new release (don't know about any other changes).

**Comment by marc-hanheide** [comment]
Ok, does this effect any of the ILIAD launch files we are using?

**Comment by h72a65** [comment]
Good question. Which are you using :-). The problem that I see now is that the fork topic has changed.

**Comment by marc-hanheide** [comment]
@MFernandezCarmona @martinmagnusson 

Please be aware

**Comment by h72a65** [comment]
I've fixed that the two first examples runs now, the third is currently not working but I guess that is fine. An no I didn't change anything apart from the specific launch files used in the examples.

**Comment by MFernandezCarmona** [comment]
Hi,
Yes, I moved the fork topics and most likely to the wrong place. Can anybody add them into https://gitsvn-nt.oru.se/iliad/software/iliad_metapackage/wikis/naming-conventions-in-iliad ?

I will have a look to @h72a65 changes about calibration, but I'm trying to have those in yaml files instead of arguments of launch files. Can you point me any of those changes?

**Comment by h72a65** [comment]
Regarding the 'calibration', that was a request from you @MFernandezCarmona that you made a couple of weeks ago and while adding this I had to manually merge this file:  gazebo_oru/cititruck/cititruck_description/urdf/iliad_velodyne_cititruck.xacro so if this is all good I don't think there is much to check, I didn't add anything there myself.

**Pull request merged**
